vich_uploader:
    db_driver: orm

    metadata:
        type: attribute

    #mappings:
        #media:
            #uri_prefix: /uploads/media
            #upload_destination: '%media_directory%'
            #namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

